FROM ubuntu

ARG USER
ARG UID
ARG GO_VERSION=go

RUN apt-get update && \
    apt-get -y install git gcc make vim zip xz-utils curl jq gpgconf tmux zsh language-pack-en sudo && \
    apt-get install -y ruby-full build-essential zlib1g-dev git && \
    useradd -u ${UID} -ms /bin/zsh ${USER} && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/${USER}

WORKDIR /home/$USER

USER $USER

#RUN git config --global --add safe.directory /host && \
RUN git clone https://github.com/kevydotvinu/dotfiles && \
    cd dotfiles && make nvim && make ohmyzsh && make go GO_VERSION=${GO_VERSION} && make fzf

CMD /usr/bin/zsh
